softeerbootcamp-2nd/H7-WantCar

- frontend/src/components/Header/Exit/Exit.jsx
- frontend/src/components/Header/Exit/ExitStyle.jsx
- frontend/src/components/Header/Header.jsx
- frontend/src/components/Header/HeaderStyle.jsx
- frontend/src/components/Header/Logo/Logo.jsx
- frontend/src/components/Header/Logo/LogoStyle.jsx
- frontend/src/components/Header/Nav/Nav.jsx
- frontend/src/components/Header/Nav/NavStyle.jsx
- frontend/src/pages/Home/Home.jsx
> [Front-End] 헤더 컴포넌트 추가

- frontend/src/components/TrimCard/TrimCard.jsx
- frontend/src/components/TrimCard/TrimCardStyle.jsx
> feat: Trim Card 컴포넌트 추가

- frontend/src/components/HMGData/HMGData.jsx
- frontend/src/components/HMGData/HMGDataItem.jsx
- frontend/src/components/HMGData/HMGDataStyle.jsx
> [Front-End] feat: HMG 데이터 컴포넌트 추가

- frontend/src/components/Header/Exit/ExitStyle.jsx
- frontend/src/components/Header/HeaderStyle.jsx
- frontend/src/components/Header/Logo/Logo.jsx
- frontend/src/components/Header/Logo/LogoStyle.jsx
- frontend/src/components/Header/Nav/Nav.jsx
- frontend/src/components/Header/Nav/NavStyle.jsx
> [Front-End] style: Header 스타일 수정

- frontend/src/pages/Home/Select/Select.jsx
- frontend/src/pages/Home/Select/SelectStyle.jsx
> [Front-End] feat: 트림 선택 카드 구현

- frontend/src/pages/Home/Home.jsx
- frontend/src/pages/Home/HomeStyle.jsx
> [Front-End] feat: 메인 페이지 레이아웃 구현

- frontend/src/pages/TrimSelectPage/Pick/TrimCard/index.jsx
- frontend/src/pages/TrimSelectPage/Pick/index.jsx
> [Front-End] feat: 트림선택 카드 한번에 하나만 선택되게 변경

- frontend/src/components/PickTitle/index.jsx
- frontend/src/components/PickTitle/style.jsx
- frontend/src/pages/ExteriorColorPage/Pick/index.jsx
- frontend/src/pages/InteriorColorPage/Pick/index.jsx
- frontend/src/pages/ModelTypePage/Pick/index.jsx
- frontend/src/pages/TrimSelectPage/Pick/index.jsx
- frontend/src/pages/TrimSelectPage/Pick/style.jsx
> feat: PickTitle 컴포넌트 구현

- frontend/src/pages/TrimSelectPage/Info/TrimImage/style.jsx
- frontend/src/pages/TrimSelectPage/Info/style.jsx
> [Front-End] design: 트림 선택 페이지 레이아웃 수정

- frontend/src/pages/ModelTypePage/Info/HMGData/HMGChart/index.jsx
- frontend/src/pages/ModelTypePage/Info/HMGData/HMGChart/style.jsx
- frontend/src/pages/ModelTypePage/Info/HMGData/index.jsx
- frontend/src/pages/ModelTypePage/Info/HMGData/style.jsx
> [Front-End] feat: HMG 데이터 그래프 구현

- .github/workflows/SpringAPIDeploy
- .github/workflows/SpringAPIDeploy.yml
- backend/appspec.yml
- backend/deploy.sh
> 자동 배포 기능 구현 #72

- frontend/src/components/Section/index.jsx
- frontend/src/components/Section/style.jsx
- frontend/src/pages/AddOptionPage/Info/index.jsx
- frontend/src/pages/AddOptionPage/Info/style.jsx
- frontend/src/pages/AddOptionPage/index.jsx
- frontend/src/pages/ModelTypePage/Info/index.jsx
- frontend/src/pages/ModelTypePage/Info/style.jsx
- frontend/src/pages/ModelTypePage/index.jsx
> [Front-End] feat: Section 레이아웃 수정

- frontend/src/components/Popup/style.jsx
> [Front-End] design: 팝업 컴포넌트 스타일 수정

- backend/src/main/java/softeer/wantcar/cartalog/config/WebConfig.java
- backend/src/main/resources/application.yml
> [Backend] CORS 설정 추가

- frontend/src/components/Button/style.jsx
- frontend/src/components/RoundButton/index.jsx
- frontend/src/components/RoundButton/style.jsx
- frontend/src/pages/ModelTypePage/Pick/index.jsx
> [Front-End] feat: RoundButton 컴포넌트 구현

- frontend/.eslintrc.cjs
> [Front-End] fix: eslint 작동 안하는 문제 수정

- frontend/src/components/Toggle/index.jsx
- frontend/src/components/Toggle/style.jsx
Close #100 
사용 예시:
``` js
function ToggleTestPage() {
const [isInterior, setIsInterior] = useState(false);
return (
<div style={{ padding: '100px', display: 'flex', gap: '40px' }}>
<Toggle big state={isInterior} setState={setIsInterior} />
</div>
);
}
```
> [Front-End] feat: 내외장 토글 구현

- .github/workflows/SpringAPIDeploy.yml
PR closed도 push의 일종이라 두번 배포되는 현상을 수정하였습니다.
> [BackEnd] 배포가 두번 되는 심각한 현상 패치#104

- frontend/src/pages/ExteriorColorPage/Pick/index.jsx
- frontend/src/pages/ExteriorColorPage/Pick/style.jsx
> feat: 외장 색상 Pick영역 레이아웃 구성

- backend/src/main/java/softeer/wantcar/cartalog/entity/Color.java
- backend/src/main/java/softeer/wantcar/cartalog/model/controller/ModelController.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/controller/TrimColorController.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/controller/TrimController.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/dto/TrimExteriorColorListResponseDto.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/dto/TrimInteriorColorListResponseDto.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/dto/TrimListResponseDto.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/service/MockTrimColorService.java
- backend/src/test/java/softeer/wantcar/cartalog/model/controller/ModelControllerTest.java
- backend/src/test/java/softeer/wantcar/cartalog/trim/controller/TrimColorControllerTest.java
- backend/src/test/java/softeer/wantcar/cartalog/trim/controller/TrimControllerTest.java
> [Backend] MockData 잘못된 데이터 수정#137

- frontend/src/components/CheckIcon/index.jsx
- frontend/src/components/ColorCard/index.jsx
- frontend/src/components/ColorCard/style.jsx
- frontend/src/components/ColorChip/index.jsx
- frontend/src/components/ColorChip/style.jsx
- frontend/src/components/TypeCard/index.jsx
- frontend/src/components/TypeCard/style.jsx
- frontend/src/styles/GlobalStyle.jsx
> [Front-End] 카드 컴포넌트 공통 스타일 분리, 타입 선택 카드 추가

- .github/workflows/SpringAPIDeploy.yml
- backend/.gitignore
- backend/deploy.sh
- backend/src/main/java/softeer/wantcar/cartalog/trim/controller/TrimController.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/dto/TrimListResponseDto.java
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application.yml
- backend/src/test/java/softeer/wantcar/cartalog/trim/controller/TrimControllerTest.java
> [Backend] 설정 파일 분리 #140

- backend/build.gradle
- backend/src/test/java/softeer/wantcar/cartalog/CartalogApplicationTests.java
- backend/src/test/resources/application.yml
- backend/src/test/resources/schema.sql
- 스프링 데이터베이스 테스트 초기 설정 완료
- 따로 데이터베이스를 연결하지 않고 테스트가 가능하도록 설정 완료
> [Backend] 스프링 데이터베이스 테스트 초기 설정 완료

- frontend/src/components/TypeCard/style.jsx
- frontend/src/pages/ModelTypePage/Pick/PickCard/index.jsx
- frontend/src/pages/ModelTypePage/Pick/PickCard/style.jsx
- frontend/src/pages/ModelTypePage/Pick/constants.js
- frontend/src/pages/ModelTypePage/Pick/index.jsx
- frontend/src/pages/ModelTypePage/Pick/style.jsx
- frontend/src/pages/ModelTypePage/index.jsx
- frontend/src/styles/GlobalStyle.jsx
- frontend/src/utils/Context/index.jsx
> [Front-End] ModelType API 연동 설정

- frontend/src/components/Title/style.jsx
- frontend/src/pages/TrimSelectPage/Info/HMGData/index.jsx
- frontend/src/pages/TrimSelectPage/Info/HMGData/style.jsx
- frontend/src/pages/TrimSelectPage/Info/TrimImage/index.jsx
- frontend/src/pages/TrimSelectPage/Info/index.jsx
- frontend/src/pages/TrimSelectPage/Pick/index.jsx
- frontend/src/pages/TrimSelectPage/index.jsx
- frontend/src/styles/GlobalStyle.jsx
> [Front-End] feat: 트림 선택 페이지 API 연결

- frontend/src/components/NextButton/constants.js
- frontend/src/components/NextButton/index.jsx
- frontend/src/components/NextButton/style.jsx
- frontend/src/pages/ModelTypePage/Pick/index.jsx
- frontend/src/pages/ModelTypePage/index.jsx
- frontend/src/styles/GlobalStyle.jsx
- frontend/src/utils/Context/index.jsx
총 가격 연동 완료
다음으로 이동 이벤트 연결 (예정)
견적요약 이동 이벤트 연결 (예정)
close #165
> [Front-End] NextButton 컴포넌트 구현

- frontend/src/components/Footer/index.jsx
- frontend/src/components/Footer/style.jsx
- frontend/src/components/NextButton/style.jsx
- frontend/src/components/PageLayout/index.jsx
- frontend/src/pages/ModelTypePage/Pick/HMGData/HMGUnit/index.jsx
- frontend/src/pages/ModelTypePage/Pick/HMGData/HMGUnit/style.jsx
- frontend/src/pages/ModelTypePage/Pick/HMGData/constants.js
- frontend/src/pages/ModelTypePage/Pick/HMGData/index.jsx
- frontend/src/pages/ModelTypePage/Pick/HMGData/style.jsx
- frontend/src/pages/ModelTypePage/Pick/index.jsx
- frontend/src/pages/ModelTypePage/Pick/style.jsx
- frontend/src/pages/ModelTypePage/index.jsx
- frontend/src/utils/Context/index.jsx
Footer는 페이지 영역 state에 따라서 배경이 생긴다.
Page는 1부터 6까지의 범위로 지정한다.
close #58
> [Front-End] ModelType의 Pick영역 구현

- frontend/src/pages/ExteriorColorPage/Pick/index.jsx
- frontend/src/pages/ExteriorColorPage/Pick/style.jsx
- frontend/src/pages/ExteriorColorPage/constants.js
- frontend/src/pages/ExteriorColorPage/index.jsx
- frontend/src/pages/ModelTypePage/Pick/style.jsx
- frontend/src/utils/Context/index.jsx
> [Front-End] 외장색상 Pick 영역 구현 & API 연결

- frontend/src/pages/ExteriorColorPage/Info/TrimImage/index.jsx
- frontend/src/pages/ExteriorColorPage/Info/TrimImage/style.jsx
- frontend/src/pages/ExteriorColorPage/Info/TrimStand/index.jsx
- frontend/src/pages/ExteriorColorPage/Info/TrimStand/style.jsx
- frontend/src/pages/ExteriorColorPage/Info/index.jsx
- frontend/src/pages/ExteriorColorPage/Pick/index.jsx
- frontend/src/pages/ExteriorColorPage/constants.js
- frontend/src/pages/ExteriorColorPage/index.jsx
- frontend/src/utils/Context/index.jsx
> [Front-End] 외장색상 페이지 API 연동

- frontend/src/pages/AddOptionPage/OptionCard/index.jsx
- frontend/src/pages/AddOptionPage/OptionCard/style.jsx
> [Front-End] feat: 옵션 선택 카드 컴포넌트 추가

- frontend/src/components/PriceStaticBar/style.jsx
- frontend/src/styles/themes.jsx
> [Front-End] fix: 슬라이더 스크롤 되는 문제, 완료 페이지 폰트 깨지는 문제 수정

- frontend/src/components/Button/index.jsx
- frontend/src/components/NextButton/constants.js
- frontend/src/components/NextButton/index.jsx
- frontend/src/pages/ExteriorColorPage/Pick/index.jsx
- frontend/src/pages/InteriorColorPage/Pick/index.jsx
- frontend/src/pages/ModelTypePage/Pick/index.jsx
- frontend/src/pages/OptionPickerPage/Pick/index.jsx
- frontend/src/pages/OptionPickerPage/Pick/style.jsx
> [Front-End] NextButton 컴포넌트 navigate 추가 구현

- frontend/src/pages/TrimSelectPage/Info/HMGData/index.jsx
- frontend/src/pages/TrimSelectPage/Info/HMGData/style.jsx
- frontend/src/pages/TrimSelectPage/Info/TrimImage/index.jsx
- frontend/src/pages/TrimSelectPage/Info/index.jsx
- frontend/src/pages/TrimSelectPage/Pick/TrimCard/index.jsx
- frontend/src/pages/TrimSelectPage/Pick/index.jsx
- frontend/src/pages/TrimSelectPage/constants.js
- frontend/src/pages/TrimSelectPage/index.jsx
- frontend/src/utils/Context/index.jsx
> [Front-End] 트림선택 페이지 API 연결

- frontend/src/pages/ExteriorColorPage/Info/TrimImage/index.jsx
- frontend/src/pages/ExteriorColorPage/index.jsx
- frontend/src/pages/InteriorColorPage/index.jsx
- frontend/src/pages/ModelTypePage/Pick/PickCard/index.jsx
- frontend/src/pages/ModelTypePage/Pick/index.jsx
- frontend/src/pages/ModelTypePage/constants.js
- frontend/src/pages/ModelTypePage/index.jsx
- frontend/src/pages/TrimSelectPage/Pick/TrimCard/index.jsx
- frontend/src/pages/TrimSelectPage/index.jsx
- frontend/src/utils/Context/index.jsx
> [Front-End] 모델타입 페이지 API 연동

- backend/src/main/java/softeer/wantcar/cartalog/trim/repository/TrimQueryRepositoryImpl.java
> [Backend] 트림 목록 조회 API 실 사용 데이터 양식 변경 #198

- .github/workflows/FrontendCD.yml
> [Front-End] 자동 배포 액션 추가

- backend/src/test/resources/csv/trims.csv
> [Backend] 메인 페이지에 필요한 기본 트림 이미지 데이터 수정 #205

- frontend/src/pages/OptionPickerPage/OptionCard/index.jsx
- frontend/src/pages/OptionPickerPage/OptionCard/style.jsx
> [Front-End] feat: 옵션 선택 카드 동작 분리

- backend/src/main/java/softeer/wantcar/cartalog/model/repository/ModelOptionQueryRepositoryImpl.java
> [Backend] 모델 타입 식별자를 통해 모델 타입 유형을 가져오지 못하는 문제 #212

- backend/src/main/java/softeer/wantcar/cartalog/entity/trim/Trim.java
- backend/src/main/java/softeer/wantcar/cartalog/global/ServerPaths.java
- backend/src/main/java/softeer/wantcar/cartalog/global/utils/CompareUtils.java
- backend/src/main/java/softeer/wantcar/cartalog/model/controller/ModelController.java
- backend/src/main/java/softeer/wantcar/cartalog/model/dto/ModelTypeListResponseDto.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/controller/TrimColorController.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/controller/TrimController.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/dto/TrimExteriorColorListResponseDto.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/repository/QueryString.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/repository/TrimColorQueryRepository.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/repository/TrimColorQueryRepositoryImpl.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/repository/TrimTestRepository.java
- backend/src/test/java/softeer/wantcar/cartalog/trim/controller/TrimColorControllerTest.java
- backend/src/test/java/softeer/wantcar/cartalog/trim/repository/TrimColorQueryRepositoryImplTest.java
- 트림 외장 색상 목록 레파지토리 구현
- 트림 외장 색상 목록 조회 컨트롤러 구현
- 비교 Util 추가
- 서버 경로 클래스 추가
> [Backend] 트림 외장 색상 목록 조회 API 구현 #114

- frontend/src/components/PriceStaticBar/index.jsx
- frontend/src/components/Section/index.jsx
- frontend/src/pages/EstimationPage/index.jsx
- frontend/src/pages/ModelTypePage/Info/HMGData/HMGChart/index.jsx
- frontend/src/pages/ModelTypePage/Info/HMGData/index.jsx
- frontend/src/pages/ModelTypePage/Pick/PickCard/index.jsx
- frontend/src/pages/ModelTypePage/constants.js
- frontend/src/pages/TrimSelectPage/Info/HMGData/index.jsx
- frontend/src/pages/TrimSelectPage/Pick/TrimCard/index.jsx
- frontend/src/pages/TrimSelectPage/Pick/index.jsx
- frontend/src/pages/TrimSelectPage/index.jsx
- frontend/src/utils/Context/index.jsx
```jsx
trimFetch: [],
isTrimFetch: false,
trimId: 1,
```
`trimFetch` fetch받아온 데이터
`isTrimFetch` fetch로 API를 다시 안받아오도록 설정
`trimId` 선택한 trimId 저장
트림 API 패치
```jsx
const response = await fetch('http://3.36.126.30/models/trims?basicModelId=1');
```
`page` 모델타입페이지에 올때마다 page설정
트림선택페이지로 돌아오면 이전 fetch상태 초기화
```jsx
useEffect(() => {
async function fetchData() {
if (!trim.isTrimFetch) {
const response = await fetch('http://3.36.126.30/models/trims?basicModelId=1');
const dataFetch = await response.json();
setTrimState((prevState) => ({
...prevState,
trim: {
...prevState.trim,
trimFetch: [...dataFetch.trims],
isTrimFetch: true,
},
}));
}
setTrimState((prevState) => ({ ...prevState, page: 1 }));
}
fetchData();
setTrimState((prevState) => ({
...prevState,
modelType: {
...prevState.modelType, …
```
> [Front-End] 트림선택 API 연동 수정 및 Context API 수정

- frontend/src/pages/TrimSelectPage/Pick/TrimCard/index.jsx
> [Front-End] 트림선택 API 변경 내용 반영

- backend/src/main/java/softeer/wantcar/cartalog/trim/dto/TrimExteriorColorListResponseDto.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/repository/QueryString.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/repository/TrimColorQueryRepositoryImpl.java
- backend/src/test/resources/csv/model_exterior_colors.csv
- backend/src/test/resources/csv/model_options.csv
- backend/src/test/resources/schema.sql
- 외장 색상의 잘못된 주소 경로를 수정한다.
- 차 이미지 -> 차 이미지 보관 디렉토리로 수정한다.
- CarImageUrl -> CarImageDirectory
- db 스키마의 변경이 포함되어 있습니다.
- 구동 방식 이미지 확장자 jpg -> png 수정
> [Backend] 잘못된 주소 경로 수정 #230

- frontend/src/pages/OptionPickerPage/Pick/index.jsx
- frontend/src/utils/Context/index.jsx
* State key 이름 변경: `selectedOptions` => `optionPicker`
> [Front-End] fix: State key 이름 수정

- backend/src/main/java/softeer/wantcar/cartalog/model/controller/ModelController.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/controller/TrimColorController.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/controller/TrimController.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/dto/TrimInteriorColorListResponseDto.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/repository/QueryString.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/repository/TrimColorQueryRepository.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/repository/TrimColorQueryRepositoryImpl.java
- backend/src/test/java/softeer/wantcar/cartalog/trim/controller/TrimColorControllerTest.java
- backend/src/test/java/softeer/wantcar/cartalog/trim/repository/TrimColorQueryRepositoryImplTest.java
- 내장 색상 목록 조회 api 구현
- swagger 버그 수정
- 적절한 swagger 예제로 수정
> [Backend] 트림 내장 색상 목록 조회 API 구현 #115

- frontend/src/components/Section/index.jsx
- frontend/src/pages/EstimationPage/index.jsx
- frontend/src/pages/ExteriorColorPage/Pick/index.jsx
- frontend/src/pages/ExteriorColorPage/index.jsx
- frontend/src/pages/InteriorColorPage/Info/index.jsx
- frontend/src/pages/InteriorColorPage/Pick/index.jsx
- frontend/src/pages/InteriorColorPage/index.jsx
- frontend/src/pages/ModelTypePage/Pick/HMGData/index.jsx
- frontend/src/pages/ModelTypePage/index.jsx
- frontend/src/pages/TrimSelectPage/Info/index.jsx
- frontend/src/pages/TrimSelectPage/Pick/index.jsx
- frontend/src/utils/Context/index.jsx
```jsx
fetchData: [],
isFetch: false,
code: null,
name: null,
carImageUrl: null,
count: 1,
page: null,
position: null,
```
`fetchData` fetch받아온 데이터
`isFetch` fetch로 API를 다시 안받아오도록 설정 (외장색상 달라지면 다시 받아옴)
`code` 선택한 내장색상 저장
`page` 내장색상카드 페이지
`position` 내장색상카드 위치
내장색상 API 패치
```jsx
const response = await fetch(`http://3.36.126.30/models/trims/interior-colors?exteriorColorCode=${exteriorColor.code}&trimId=${trim.id}`);
```
```jsx
useEffect(() => {
async function fetchData() {
if (!interiorColor.isFetch) {
const response = await fetch(
`http://3.36.126.30/models/trims/interior-colors?exteriorColorCode=${exteriorColor.code}&trimId=${trim.id}`,
);
const dataFetch = await response.json();
const defaultData = dataFetch.interiorColors.find(
(data) => data.code === interiorColor.code,
); …
```
> [Front-End] 내장색상 API 연동

- frontend/src/pages/ModelTypePage/index.jsx
- frontend/src/pages/TrimSelectPage/Pick/TrimCard/index.jsx
- frontend/src/pages/TrimSelectPage/Pick/index.jsx
- frontend/src/utils/Context/index.jsx
> [Front-End] default 값 설정 state 생성 및 반영 

- Android/app/src/main/java/com/softeer/cartalog/ui/activity/MainActivity.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/adapter/BindingAdapters.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/adapter/ButtonBindingAdapters.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/adapter/TypeDetailPopupAdapter.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/dialog/PriceSummaryBottomSheetFragment.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/fragment/TrimFragment.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/view/TypeSelectView.kt
- Android/app/src/main/res/layout/activity_main.xml
- Android/app/src/main/res/layout/fragment_price_summary_bottom_sheet.xml
- Android/app/src/main/res/layout/fragment_trim.xml
- Android/app/src/main/res/layout/item_type_detail_popup.xml
- Android/app/src/main/res/layout/view_typeselect.xml
> [Android] Databinding에 Activity나 Fragment 주입한 이슈 해결 #210

- frontend/src/pages/ModelTypePage/Info/HMGData/HMGChart/style.jsx
- frontend/src/pages/ModelTypePage/Info/style.jsx
* 모델타입 선택 페이지에서 옵션 변경 시 그래프 부드럽게 변하도록 애니메이션 추가
* #256
> [Front-End] feat: 모델타입 선택 페이지 그래프 애니메이션 추가

- frontend/src/pages/EstimationPage/Preview/index.jsx
- frontend/src/pages/EstimationPage/Preview/style.jsx
그라데이션 width가 페이지 width보다 작은 문제 수정
* Close #258
> [Front-End] fix: 완료 페이지 그라데이션 배경 너비 수정

- frontend/src/pages/EstimationPage/HMGArea/SimilarCard/index.jsx
- frontend/src/pages/EstimationPage/HMGArea/SimilarCard/style.jsx
* 유사견적 그래프가 화면에 보일 때 애니메이션 시작하도록 수정
* 컴포넌트가 화면 밖으로 나갔다가 다시 들어오면 애니메이션 재시작
* Close #268
> [Front-End] feat: 유사견적 그래프 useIntersectionObserver 이용 애니메이션 개선

- frontend/src/pages/EstimationPage/HMGArea/SimilarCard/index.jsx
- frontend/src/pages/EstimationPage/Preview/index.jsx
- frontend/src/pages/EstimationPage/Preview/style.jsx
- frontend/src/pages/EstimationPage/index.jsx
- frontend/src/pages/EstimationPage/style.jsx
완료 페이지 스크롤 시 미리보기 영역 애니메이션 제거
* Close #275
> [Front-End] feat: 완료 페이지 타이틀 애니메이션 제거

- frontend/src/pages/EstimationPage/index.jsx
- frontend/src/utils/Context/index.jsx
> [Front-End] 완료페이지 트랜지션 적용

- frontend/src/pages/ModelTypePage/index.jsx
- frontend/src/pages/TrimSelectPage/Pick/TrimCard/index.jsx
> [Front-End] 외장색상, 내장색상 API 수정

- frontend/src/components/Header/Exit/style.jsx
* svg 아이콘 색상 투명한 문제 해결
* Close #296
> [Front-End] design: exit 아이콘 색 추가

- backend/src/test/resources/schema.sql
> [Backend] 사용자 데이터 및 견적서 테이블 생성 #271

- frontend/src/components/Header/Nav/index.jsx
- frontend/src/components/Header/Nav/style.jsx
- frontend/src/components/SummaryPopup/index.jsx
- frontend/src/components/SummaryPopup/style.jsx
- frontend/src/pages/ModelTypePage/Pick/HMGData/index.jsx
- frontend/src/pages/OptionPickerPage/index.jsx
- frontend/src/pages/TrimSelectPage/Pick/index.jsx
- frontend/src/utils/Context/index.jsx
> [Front-End] 옵션페이지 API 세팅

- backend/src/main/java/softeer/wantcar/cartalog/trim/repository/QueryString.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/repository/TrimOptionQueryRepositoryImpl.java
> [Backend] 해시태그 미제공 버그 수정 #311

- frontend/src/components/Interaction/index.jsx
- frontend/src/components/Section/style.jsx
- frontend/src/pages/EstimationPage/Preview/style.jsx
- frontend/src/pages/EstimationPage/style.jsx
- frontend/src/pages/ExteriorColorPage/Pick/style.jsx
- frontend/src/pages/InteriorColorPage/Pick/style.jsx
- frontend/src/pages/ModelTypePage/Pick/style.jsx
- frontend/src/pages/OptionPickerPage/Pick/style.jsx
* 한 페이지에서 스크롤 해도 다른 페이지에 영향 미치지 않음
* Close #314
> [Front-End] 페이지마다 따로 스크롤할 수 있도록 분리 Fe feature/#314

- frontend/src/components/Footer/index.jsx
- frontend/src/components/Footer/style.jsx
- frontend/src/components/Interaction/index.jsx
- frontend/src/components/Section/index.jsx
- frontend/src/pages/ExteriorColorPage/Pick/index.jsx
- frontend/src/pages/ExteriorColorPage/Pick/style.jsx
- frontend/src/pages/ExteriorColorPage/index.jsx
- frontend/src/pages/InteriorColorPage/Pick/index.jsx
- frontend/src/pages/InteriorColorPage/Pick/style.jsx
- frontend/src/pages/InteriorColorPage/index.jsx
- frontend/src/pages/ModelTypePage/Pick/HMGData/index.jsx
- frontend/src/pages/ModelTypePage/Pick/index.jsx
- frontend/src/pages/ModelTypePage/Pick/style.jsx
- frontend/src/pages/ModelTypePage/index.jsx
- frontend/src/pages/OptionPickerPage/Pick/index.jsx
- frontend/src/pages/OptionPickerPage/Pick/style.jsx
- frontend/src/pages/OptionPickerPage/index.jsx
- frontend/src/pages/TrimSelectPage/index.jsx
- frontend/src/utils/Context/index.jsx
> [Front-End] Footer를 Section에서 분리해서 Fixed 적용하기

- frontend/src/components/Footer/index.jsx
- frontend/src/components/Footer/style.jsx
- frontend/src/pages/ModelTypePage/Pick/style.jsx
* 첫 페이지에서 푸터가 사라지는 애니메이션이 표시되는 문제 수정
* 모델 타입 선택 페이지에서 의도하지 않은 스크롤 수정
* Close #319
> [Front-End] fix: 첫 페이지에서 footer가 잠깐 보이는 문제 수정

- frontend/src/components/Interaction/index.jsx
- frontend/src/components/PriceStaticBar/Slider/index.jsx
- frontend/src/components/PriceStaticBar/constant.js
- frontend/src/components/PriceStaticBar/index.jsx
- frontend/src/components/PriceStaticBar/style.jsx
- frontend/src/pages/TrimSelectPage/Pick/TrimCard/index.jsx
- frontend/src/pages/TrimSelectPage/Pick/index.jsx
- frontend/src/utils/Context/index.jsx
- 예산설정 슬라이더 애니메이션 적용
- minPrice, maxPrice, budget 상태설정
- close #317
> [Front-End] 첫페이지에서 예산설정 슬라이더 보이지 않게

- frontend/src/pages/OptionPickerPage/Info/index.jsx
- frontend/src/pages/OptionPickerPage/OptionCard/index.jsx
- frontend/src/pages/OptionPickerPage/OptionCard/style.jsx
- frontend/src/pages/OptionPickerPage/Pick/CategorySelector/index.jsx
- frontend/src/pages/OptionPickerPage/Pick/index.jsx
- frontend/src/pages/OptionPickerPage/index.jsx
- frontend/src/utils/Context/index.jsx
* 옵션 선택 페이지 API 연결
* 카테고리 필터 동작 추가
* 옵션 정보 영역 API 부분 연결
* 선택한 옵션 정보 저장
* 옵션 정보 영역 완성
* 검색 기능 추가
> [Front-End] 옵션 선택 페이지 API 연결 Fe feature/#227

- Android/app/src/main/java/com/softeer/cartalog/data/repository/CarRepository.kt
- Android/app/src/main/java/com/softeer/cartalog/data/repository/CarRepositoryImpl.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/adapter/BindingAdapters.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/adapter/ButtonBindingAdapters.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/adapter/ImageBindingAdapters.kt
- Android/app/src/main/java/com/softeer/cartalog/viewmodel/ExteriorViewModel.kt
- Android/app/src/main/java/com/softeer/cartalog/viewmodel/InteriorViewModel.kt
- Android/app/src/main/java/com/softeer/cartalog/viewmodel/MainViewModel.kt
- Android/app/src/main/java/com/softeer/cartalog/viewmodel/OptionViewModel.kt
- Android/app/src/main/java/com/softeer/cartalog/viewmodel/TrimViewModel.kt
- Android/app/src/main/java/com/softeer/cartalog/viewmodel/TypeViewModel.kt
> [Android] LiveData 선언방식 관련 이슈 수정 #325

- frontend/src/components/NextButton/index.jsx
- frontend/src/components/SummaryPopup/constants.js
- frontend/src/components/SummaryPopup/index.jsx
- frontend/src/components/SummaryPopup/style.jsx
- frontend/src/pages/TrimSelectPage/Pick/TrimCard/index.jsx
- frontend/src/utils/Context/index.jsx
SummaryPopup을 누를 때마다 외장이미지, 내장이미지 두 장을 불러옴
default 데이터에서 이름, 코드, 가격까지 모두 state로 저장함
- close #323
> [Front-End] 견적 요약 API 연동

- frontend/src/pages/ModelTypePage/Info/style.jsx
* 모델 타입 선택 페이지 이미지 배경 투명하게 보이도록 수정
* Close #333
> [Front-End] design: 모델 타입 선택 페이지 이미지 배경 투명화

- frontend/src/pages/ModelTypePage/Info/HMGData/HMGChart/index.jsx
- frontend/src/pages/ModelTypePage/Info/HMGData/HMGChart/style.jsx
- frontend/src/pages/ModelTypePage/constants.js
- frontend/src/pages/ModelTypePage/index.jsx
- frontend/src/pages/OptionPickerPage/constants.js
- frontend/src/pages/OptionPickerPage/index.jsx
- frontend/src/utils/Context/index.jsx
- 최대출력, 최대토크 그래프의 width값을 API로 받아와서 적용
- 옵션페이지에 isFetch가 false면 로딩 페이지가 보이도록 반영
- close #221
> [Front-End] 최대출력, 최대토크 그래프 값 수정 및 옵션페이지 로딩 구현

- frontend/src/components/TypeCard/style.jsx
* TypeCard의 border radius 6px로 수정
* Closes #336
> [Front-End] design: TypeCard border radius 수정

- frontend/src/components/RoundButton/style.jsx
- frontend/src/components/Title/style.jsx
- frontend/src/pages/ModelTypePage/Info/HMGData/style.jsx
- frontend/src/pages/ModelTypePage/Info/style.jsx
- 모델타입 Info영역 word-break 추가 
- 모델타입 이미지 위치 변경
- RoundButton 배경색 제거
- close #336
> [Front-End] 모델타입 Info영역 word-break 추가 및 이미지 위치 변경

- backend/src/main/java/softeer/wantcar/cartalog/estimate/controller/EstimateController.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/repository/EstimateQueryRepository.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/repository/EstimateQueryRepositoryImpl.java
- backend/src/test/java/softeer/wantcar/cartalog/estimate/controller/EstimateControllerTest.java
- backend/src/test/java/softeer/wantcar/cartalog/estimate/repository/EstimateQueryRepositoryImplTest.java
특정 트림의 출고 견적에서 평균 가격을 조회하는 API를 구현하였습니다.
> [Backend] 가격 분포 데이터 조회 API 구현

- frontend/src/components/SummaryPopup/index.jsx
- frontend/src/components/SummaryPopup/style.jsx
- frontend/src/pages/ModelTypePage/Pick/PickCard/index.jsx
- frontend/src/pages/OptionPickerPage/Pick/index.jsx
- frontend/src/utils/Context/index.jsx
- 견적요약 모달 모델 타입 데이터 연동
- 견적요약 모달 옵션 데이터 연동
- close #339
> [Front-End] 견적요약 모달 옵션 데이터 연동

- frontend/src/components/SummaryPopup/InfoPanel/style.jsx
> [Front-End] 견적요약 모달 옵션 이름 길이 처리

- frontend/src/pages/OptionPickerPage/Pick/TypeSelector/index.jsx
- frontend/src/pages/OptionPickerPage/Pick/TypeSelector/style.jsx
* 추가옵션 / 기본옵션 전환할 때 하단 인디케이터 바 추가
* 인디케이터 바 애니메이션 추가
https://github.com/softeerbootcamp-2nd/H7-WantCar/assets/38831776/f97a367d-6f4d-4a33-9440-fd17a469be66
* Close #358
> [Front-End] feat: 옵션 선택 페이지 기본/추가옵션 인디케이터 추가

- frontend/src/components/ImageViewButton/index.jsx
- frontend/src/components/ImageViewButton/style.jsx
* 이미지 확인 버튼 추가
```javascript
<ImageViewButton
onClick={handleClick}
text='이미지 확인'
/>
```
* onClick: 버튼 클릭 시 실행할 함수
* text: 버튼에 표시될 텍스트
* Close #361
> [Front-End] feat: 이미지 확인 버튼 추가

- frontend/src/pages/EstimationPage/Footer/style.jsx
> design: 완료페이지 Footer 마진 수정

- frontend/assets/icons/arrow_left.svg
- frontend/assets/icons/arrow_right.svg
- frontend/src/pages/OptionPickerPage/Info/PackageInfo/Selector/index.jsx
- frontend/src/pages/OptionPickerPage/Info/PackageInfo/Selector/style.jsx
- frontend/src/pages/OptionPickerPage/Info/PackageInfo/index.jsx
- frontend/src/pages/OptionPickerPage/Info/PackageInfo/style.jsx
- frontend/src/pages/OptionPickerPage/Info/index.jsx
* 패키지 옵션 상세 보기 추가
* 패키지 상세 보기 페이지 이동 기능 추가
* HMG data 보기 추가
* 검색 기능 추가
> [Front-End] 패키지 옵션 상세보기 추가

- frontend/src/pages/EstimationPage/Footer/index.jsx
- frontend/src/pages/EstimationPage/Footer/style.jsx
> [Front-End] 견적완료 페이지 Footer 하단 고정

- frontend/src/pages/ExteriorColorPage/Pick/index.jsx
- frontend/src/pages/InteriorColorPage/Pick/index.jsx
- 외장색상 선택 시 내장, 옵션 초기화
- 내장색상 선택시 옵션 초기화
- #370
> [Front-End] 외장색상, 내장색상 선택 시 옵션 초기화

- frontend/src/components/Header/Exit/style.jsx
- frontend/src/components/Header/Logo/style.jsx
- frontend/src/pages/ExteriorColorPage/Info/TrimImage/style.jsx
- frontend/src/pages/TrimSelectPage/Info/TrimImage/style.jsx
- frontend/src/pages/TrimSelectPage/Pick/TrimCard/style.jsx
- 트림 이미지, 트림선택 카드
- 헤더 로고, 헤더 종료 버튼
- 외장색상 360도 사진
- #373
> [Front-End] cursor pointer 기능 추가

- frontend/src/components/SearchBar/index.jsx
- frontend/src/components/SearchBar/style.jsx
* 검색 바 컴포넌트 추가
```javascript
<SearchBar
placeholder="검색어를 입력하세요"
value={searchText}
onChange={({ target }) => setSearchText(target.value)}
onSubmit={() => {handleSubmit(searchText)}}
/>
```
* `placeholder`: 검색바의 플레이스홀더 텍스트
* `value`: 검색할 텍스트
* `onChange`: 검색할 텍스트를 업데이트하는 함수
* `onSubmit`: submit하는 함수
* Close #384
> [Front-End] feat: 검색 바 컴포넌트 추가

- frontend/src/components/Header/Exit/index.jsx
- frontend/src/components/Header/Logo/index.jsx
- frontend/src/components/Header/Logo/style.jsx
- frontend/src/components/Header/constants.js
- frontend/src/components/Popup/style.jsx
- 헤더의 Logo, Exit 모달 연결
- 취소 버튼에 close 이벤트가 적용이 안되는 문제
- #382
> [Front-End] 헤더의 Logo, Exit 모달 연결

- frontend/src/components/SummaryPopup/style.jsx
> [Front-End] 견적요약 모달 스타일 수정

- frontend/src/components/PriceStaticBar/SliderMark/index.jsx
- frontend/src/components/PriceStaticBar/SliderMark/style.jsx
- frontend/src/components/PriceStaticBar/index.jsx
- 예산 범위 모달에 현재 가격을 볼 수 없는 문제 수정
- #371
> [Front-End] 예산 범위 모달에 현재 가격 기능 추가

- backend/src/main/java/softeer/wantcar/cartalog/trim/repository/TrimOptionQueryRepositoryImpl.java
> [Backend] 옵션 패키지 상세 정보 조회 #410

- backend/src/main/java/softeer/wantcar/cartalog/estimate/service/EstimateServiceImpl.java
> [Backend] 옵션 또는 패키지가 선택되지 않은 견적서의 유사 견적 개수 조회 시 에러가 발생하는 문제 해결

- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/EstimationPage/Detail/index.jsx
- frontend/src/pages/EstimationPage/Footer/index.jsx
- frontend/src/pages/EstimationPage/HMGArea/index.jsx
- frontend/src/pages/EstimationPage/index.jsx
- frontend/src/pages/EstimationPage/style.jsx
- PDF 다운로드 기능 추가
- PDF media print 설정
- #379
> [Front-End] PDF 다운로드 기능 추가

- frontend/src/pages/EstimationPage/Detail/DetailCard/DetailItem/index.jsx
- frontend/src/pages/EstimationPage/Detail/DetailCard/DetailItem/style.jsx
- frontend/src/pages/EstimationPage/Detail/DetailCard/style.jsx
> [Front-End] 수정하기 기능 삭제

- Android/app/src/main/java/com/softeer/cartalog/ui/activity/MainActivity.kt
- Android/app/src/main/java/com/softeer/cartalog/viewmodel/MainViewModel.kt
- Android/app/src/main/res/layout/dialog_exit.xml
- Android/app/src/main/res/values/strings.xml
처음부터 시작하기 -> 탭color 초기화 및 첫번째 프래그먼트로 이동, 추후 RoomDB 초기화 구현 필요 @JoYehyun99 
저장하고 종료하기 -> 앱 종료, 추후 돌아왔을 때 저장된 정보 불러오기 구현 필요
> [Android] 앱 종료 Dialog 시나리오 회의 및 구현 #407

- frontend/src/pages/EstimationPage/Footer/index.jsx
- frontend/src/pages/EstimationPage/constants.js
- 완료페이지 상담신청 버튼 클릭시, 상담신청 페이지 새탭에서 오픈
- #419
> [Front-End] 상담신청 기능 추가

- frontend/src/components/PriceStaticBar/SliderMark/index.jsx
> [Front-End] 예산 범위 모달 소수점 처리

- backend/src/main/java/softeer/wantcar/cartalog/estimate/repository/QueryString.java
> [Backend] 운영 데이터베이스에서 fuel_efficiency를 찾지 못하는 문제 해결

- Android/app/src/main/java/com/softeer/cartalog/data/local/MyCarDao.kt
- Android/app/src/main/java/com/softeer/cartalog/data/model/CarColor.kt
- Android/app/src/main/java/com/softeer/cartalog/data/model/ConfirmDetail.kt
- Android/app/src/main/java/com/softeer/cartalog/data/repository/CarRepository.kt
- Android/app/src/main/java/com/softeer/cartalog/data/repository/CarRepositoryImpl.kt
- Android/app/src/main/java/com/softeer/cartalog/data/repository/local/CarLocalDataSource.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/adapter/BindingAdapters.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/adapter/ButtonBindingAdapters.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/adapter/ConfirmDetailContentsAdapter.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/adapter/ConfirmDetailTitleAdapter.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/adapter/ImageBindingAdapters.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/fragment/ConfirmFragment.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/fragment/ExteriorFragment.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/fragment/InteriorFragment.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/fragment/TypeFragment.kt
- Android/app/src/main/java/com/softeer/cartalog/util/ItemDividerDecoration.kt
- Android/app/src/main/java/com/softeer/cartalog/util/ItemVerticalSpacingDecoration.kt
- Android/app/src/main/java/com/softeer/cartalog/viewmodel/CommonViewModelFactory.kt
- Android/app/src/main/java/com/softeer/cartalog/viewmodel/ConfirmViewModel.kt
- Android/app/src/main/java/com/softeer/cartalog/viewmodel/ExteriorViewModel.kt
- Android/app/src/main/java/com/softeer/cartalog/viewmodel/InteriorViewModel.kt
- Android/app/src/main/java/com/softeer/cartalog/viewmodel/MainViewModel.kt
- Android/app/src/main/java/com/softeer/cartalog/viewmodel/TypeViewModel.kt
- Android/app/src/main/res/drawable/btn_check_img.xml
- Android/app/src/main/res/layout/fragment_confirm.xml
- Android/app/src/main/res/layout/item_confirm_detail_container.xml
- Android/app/src/main/res/layout/item_confirm_detail_content.xml
- Android/app/src/main/res/values/colors.xml
- Android/app/src/main/res/values/strings.xml
- 앞서 선택한 차량 색깔 반영한 이미지 출력
- 선택한 옵션들 데이터 반영
|외장|내장|
|------|---|
|<img width="300" alt="0" src="https://github.com/softeerbootcamp-2nd/H7-WantCar/assets/81362348/1137d385-56eb-426d-9849-73ff967fedfe">|<img width="300" alt="1" src="https://github.com/softeerbootcamp-2nd/H7-WantCar/assets/81362348/a6c08fde-139b-48eb-97bd-b90f0b032298">|
- 스크롤 하는 경우 `이미지 확인` 버튼 생성
- 클릭시 가장 상단으로 scroll
- 예산 범위 padding 값 설정에 대한 고민
> [Android] 완료 Fragment 데이터 연동 #297

- frontend/src/pages/ExteriorColorPage/Pick/index.jsx
- frontend/src/pages/ExteriorColorPage/index.jsx
* 외장색상 이미지 png 대신 webp 이용하도록 수정
* Close #431
> [Front-End] feat: 외장색상 이미지 webp 이용하도록 수정

- frontend/src/components/Skeleton/Info/index.jsx
- frontend/src/components/Skeleton/Info/style.jsx
- frontend/src/components/Skeleton/Pick/index.jsx
- frontend/src/components/Skeleton/Pick/style.jsx
- frontend/src/components/Skeleton/index.jsx
- frontend/src/pages/ExteriorColorPage/index.jsx
- frontend/src/pages/InteriorColorPage/index.jsx
- frontend/src/pages/ModelTypePage/index.jsx
- frontend/src/pages/OptionPickerPage/index.jsx
- frontend/src/pages/TrimSelectPage/index.jsx
- Skeleton 로딩 화면 기능 추가
- Skeleton 로딩 화면 적용
- #375
> [Front-End] Skeleton 로딩 화면 기능 추가

- frontend/src/pages/OptionPickerPage/Info/Description/PackageInfo/Selector/index.jsx
- frontend/src/pages/OptionPickerPage/Info/Description/PackageInfo/Selector/style.jsx
- frontend/src/pages/OptionPickerPage/Info/Description/PackageInfo/index.jsx
- frontend/src/pages/OptionPickerPage/Info/Description/index.jsx
- frontend/src/pages/OptionPickerPage/Info/index.jsx
- frontend/src/pages/OptionPickerPage/OptionCard/style.jsx
* 패키지 옵션 하위 옵션 선택할 때 마다 미리보기 이미지가 그에 맞춰 변하도록 수정
* 패키지 옵션 페이지 전환 화살표 스타일 수정
* Close #437
> [Front-End] feat: 패키지 옵션 골랐을 때 미리보기 이미지 변하도록 수정

- backend/src/main/java/softeer/wantcar/cartalog/model/repository/QueryString.java
- 모델 옆면 및 내부 사진의 url을 가져오지 못하는 에러 수정
> [Backend] 모델 옆면 및 내부 사진의 url을 가져오지 못하는 에러 수정

- frontend/src/pages/EstimationPage/Detail/DetailCard/style.jsx
- frontend/src/pages/EstimationPage/Preview/index.jsx
* 완료 페이지 DetailContents 높이 수정
* 완료 페이지 외장 미리보기 이미지 webp로 수정
* Close #452
> [Front-End] 완료 페이지 DetailContents 높이 수정

- backend/src/main/java/softeer/wantcar/cartalog/trim/controller/TrimColorController.java
- 트림 내장 색상 조회 API의 파라미터 명세가 잘못된 문제 해결
> [Backend] 트림 내장 색상 조회 API의 파라미터 명세가 잘못된 문제 해결

- backend/src/main/java/softeer/wantcar/cartalog/chosen/ChosenConfig.java
- backend/src/main/java/softeer/wantcar/cartalog/chosen/repository/ChosenRepositoryImpl.java
- backend/src/main/java/softeer/wantcar/cartalog/chosen/repository/controller/ChosenController.java
> [Backend] 선택률 비활성화 기능 추가 #464

- frontend/src/components/PriceGraph/index.jsx
- frontend/src/components/PriceGraph/style.jsx
* 가격 분포 그래프 컴포넌트 추가
```javascript
<PriceGraph min={0} max={100} avg={40} value={40} width={200} height={100} />
```
* `min`: 최소값
* `max`: 최대값
* `avg`: 평균값
* `value`: 현재 값
* `width`: 그래프 넓이
* `height`: 그래프 높이
* Close #475
> [Front-End] feat: 가격 분포 그래프 컴포넌트 추가

- frontend/src/pages/EstimationPage/Footer/index.jsx
- frontend/src/pages/EstimationPage/Footer/style.jsx
- frontend/src/pages/EstimationPage/constants.js
- 완료페이지 이미지 확인 플로팅 버튼 제거 
- #381
> [Front-End] 완료페이지 이미지 확인 버튼 제거

- frontend/src/components/Popup/index.jsx
- frontend/src/components/PriceStaticBar/Slider/index.jsx
- frontend/src/pages/ModelTypePage/Info/HMGData/HMGChart/index.jsx
- frontend/src/pages/ModelTypePage/Info/HMGData/HMGChart/style.jsx
- frontend/src/pages/ModelTypePage/Pick/HMGData/index.jsx
- frontend/src/pages/OptionPickerPage/Info/index.jsx
> [Front-End] refactor: 리팩토링, 콘솔 오류 해결

- frontend/src/pages/EstimationPage/index.jsx
- frontend/src/pages/OptionPickerPage/Pick/index.jsx
- frontend/src/utils/Context/index.jsx
> [Front-End] 견적서 식별자 조회, 트림 평균 출고 가격 조회

- frontend/src/pages/EstimationPage/HMGArea/PriceCard/GraphArea/graph.svg
- frontend/src/pages/EstimationPage/HMGArea/PriceCard/GraphArea/index.jsx
- frontend/src/pages/EstimationPage/HMGArea/PriceCard/GraphArea/point.svg
- frontend/src/pages/EstimationPage/HMGArea/PriceCard/index.jsx
> [Front-End] 견적 가격 분포 그래프 API 연동

- Android/app/src/main/java/com/softeer/cartalog/ui/adapter/BindingAdapters.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/adapter/ButtonBindingAdapters.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/adapter/OptionSelectAdapter.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/fragment/ExteriorFragment.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/fragment/InteriorFragment.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/fragment/OptionFragment.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/fragment/TrimFragment.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/fragment/TypeFragment.kt
- Android/app/src/main/java/com/softeer/cartalog/util/ItemHorizontalSpacingDecoration.kt
- Android/app/src/main/java/com/softeer/cartalog/viewmodel/ExteriorViewModel.kt
- Android/app/src/main/java/com/softeer/cartalog/viewmodel/InteriorViewModel.kt
- Android/app/src/main/java/com/softeer/cartalog/viewmodel/OptionViewModel.kt
- Android/app/src/main/java/com/softeer/cartalog/viewmodel/TypeViewModel.kt
- Android/app/src/main/res/drawable/icon_seekbar_user_pin.xml
- Android/app/src/main/res/drawable/shape_seekbar_thumb.xml
- Android/app/src/main/res/drawable/shape_seekbar_thumb_excess.xml
- Android/app/src/main/res/layout/activity_main.xml
- Android/app/src/main/res/layout/dialog_option_detail.xml
- Android/app/src/main/res/layout/fragment_confirm.xml
- Android/app/src/main/res/layout/fragment_type.xml
- Android/app/src/main/res/layout/item_confirm_detail_container.xml
- Android/app/src/main/res/layout/item_confirm_detail_content.xml
- Android/app/src/main/res/layout/item_exterior_color.xml
- Android/app/src/main/res/layout/item_interior_color.xml
- Android/app/src/main/res/layout/item_option_select_card.xml
- Android/app/src/main/res/layout/item_trim_card.xml
- Android/app/src/main/res/layout/item_type_detail_popup.xml
> [Android] TEST 수정사항 반영 #479 

- frontend/src/pages/ModelTypePage/Pick/HMGData/index.jsx
Changes
* 모델 타입 데이터 로딩 중 배기량, 평균연비 영역에 undefined 표시되는 문제 수정
Related Issues
* Close #453
> [Front-End] fix: 모델 타입 데이터 로딩 중 undefined 표시되는 문제 수정

- frontend/src/pages/EstimationPage/Detail/style.jsx
- frontend/src/pages/EstimationPage/Footer/style.jsx
- frontend/src/pages/EstimationPage/Preview/style.jsx
- frontend/src/pages/EstimationPage/index.jsx
- frontend/src/pages/EstimationPage/style.jsx
- frontend/src/styles/GlobalStyle.jsx
* 완료 페이지 각 요소가 순차적으로 나타나는 애니메이션 추가
* Close #496
> [Front-End] feat: 완료 페이지 시작 애니메이션 추가

- frontend/src/pages/EstimationPage/HMGArea/SimilarCard/index.jsx
- frontend/src/pages/EstimationPage/HMGArea/index.jsx
- frontend/src/pages/EstimationPage/index.jsx
- frontend/src/utils/Context/index.jsx
- 유사 출고 견적 API 연동
```js
const [response, averageResponse, similarResponse] = await Promise.all([
fetch('http://3.36.126.30/estimates', {
method: 'POST',
headers: {
'Content-Type': 'application/json',
},
body: JSON.stringify({
detailTrimId: data.modelType.detailTrimId,
exteriorColorCode: data.exteriorColor.code,
interiorColorCode: data.interiorColor.code,
selectOptionOrPackageIds: data.optionPicker.chosenOptions,
}),
}),
fetch(`http://3.36.126.30/estimates/distribution?trimId=${data.trim.id}`),
fetch(`http://3.36.126.30/?estimateId=${data.estimation?.id}`),
]);
```
> [Front-End] 유사 출고 견적 API 연동

- frontend/index.html
- frontend/src/components/Header/Exit/index.jsx
- frontend/src/components/Popup/index.jsx
- frontend/src/components/Popup/style.jsx
- frontend/src/pages/EstimationPage/HMGArea/SimilarPopup/constants.js
- frontend/src/pages/EstimationPage/HMGArea/SimilarPopup/index.jsx
- 유사견적 종료 모달 구현
`exitModal` 포탈 생성
```html
<body>
<div id="modal"></div>
<div id="exitModal"></div>
<div id="root"></div>
<script type="module" src="/src/main.jsx"></script>
</body>
``
> [Front-End] 유사견적 종료 모달 구현

- frontend/src/constants.js
* constants 파일에 백엔드 URL 추가
* Close #501
> [Front-End] feat: constants 파일에 백엔드 URL 추가

- frontend/src/components/Interaction/index.jsx
- frontend/src/components/SummaryPopup/index.jsx
- frontend/src/constants.js
- frontend/src/hooks/useFetch.js
- frontend/src/pages/EstimationPage/HMGArea/SimilarPopup/index.jsx
- frontend/src/pages/EstimationPage/index.jsx
- frontend/src/pages/ExteriorColorPage/Info/index.jsx
- frontend/src/pages/ExteriorColorPage/Pick/index.jsx
- frontend/src/pages/ExteriorColorPage/constants.js
- frontend/src/pages/ExteriorColorPage/index.jsx
- frontend/src/pages/InteriorColorPage/Info/index.jsx
- frontend/src/pages/InteriorColorPage/Pick/index.jsx
- frontend/src/pages/InteriorColorPage/index.jsx
- frontend/src/pages/ModelTypePage/Info/index.jsx
- frontend/src/pages/ModelTypePage/Pick/HMGData/index.jsx
- frontend/src/pages/ModelTypePage/Pick/index.jsx
- frontend/src/pages/ModelTypePage/index.jsx
- frontend/src/pages/OptionPickerPage/Info/index.jsx
- frontend/src/pages/OptionPickerPage/index.jsx
- frontend/src/pages/TrimSelectPage/Info/index.jsx
- frontend/src/pages/TrimSelectPage/Pick/index.jsx
- frontend/src/pages/TrimSelectPage/index.jsx
- frontend/src/utils/Context/index.jsx
* Interaction의 children인 페이지 컴포넌트들에 Suspense 적용
* Close #450
> [Front-End] 페이지 컴포넌트 Suspense 사용하도록 수정

- backend/src/main/java/softeer/wantcar/cartalog/estimate/controller/EstimateController.java
- backend/src/main/java/softeer/wantcar/cartalog/model/controller/ModelController.java
- backend/src/main/java/softeer/wantcar/cartalog/similarity/controller/SimilarityController.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/controller/TrimColorController.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/controller/TrimController.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/controller/TrimOptionController.java
> [Backend] 백 주소 체계 재정비

- frontend/src/pages/ExteriorColorPage/Info/index.jsx
* 마우스 클릭 시 리렌더링 되는 문제 수정
* Close #484
> [Front-End] fix: 마우스 클릭 시 리렌더링 되는 문제 수정

- frontend/src/components/SearchBar/index.jsx
* 옵션 검색바 텍스트 변할 때 마다 검색하도록 변경
* Close #508
> [Front-End] feat: 옵션 검색바 텍스트 변할 때 마다 검색하도록 변경

- frontend/src/components/Section/index.jsx
- frontend/src/components/Section/style.jsx
- frontend/src/pages/OptionPickerPage/Info/index.jsx
- frontend/src/pages/OptionPickerPage/Info/style.jsx
- frontend/src/pages/OptionPickerPage/index.jsx
* 옵션 페이지 이미지 접기/펼치기 버튼 추가
* Close #446
> [Front-End] feat: 옵션 페이지 이미지 접기/펼치기 버튼 추가

- frontend/src/components/Chart/index.jsx
- Chart 컴포넌트 undefined 예외처리
```jsx
<S.Chart className={active ? 'active' : null}>
<div>{value?.toLocaleString() ?? 0}대</div>
<S.Bar $height={height} />
<div>{active ? '내 견적' : '유사견적'}</div>
</S.Chart>
```
- #515
> [Front-End] Chart 컴포넌트 undefined 예외처리

- frontend/src/constants.js
- API 주소 변경
```
export const URL = 'https://api.hyundei.shop/'
```
- #517
> [Front-End] API 주소 변경

- frontend/src/components/PriceCompareBar/index.jsx
- frontend/src/components/PriceCompareBar/style.jsx
* 유사견적 가격 바 컴포넌트 추가
```javascript
<PriceCompareBar min={minPrice} max={maxPrice} my={myPrice} value={valuePrice} />
```
* `min`: 견적 최소 가격
* `max`: 견적 최대 가격
* `my`: 내 견적 가격
* `value`: 비교할 유사 견적 가격
* Close #521
> [Front-End] 유사견적 가격 바 컴포넌트 추가

- backend/src/main/java/softeer/wantcar/cartalog/estimate/repository/EstimateQueryRepository.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/repository/EstimateQueryRepositoryImpl.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/repository/QueryString.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/repository/dto/EstimateInfoWithSideImageDto.java
- backend/src/main/java/softeer/wantcar/cartalog/global/utils/RowMapperUtils.java
- backend/src/main/java/softeer/wantcar/cartalog/similarity/controller/SimilarityController.java
- backend/src/main/java/softeer/wantcar/cartalog/similarity/dto/SimilarEstimate2ResponseDto.java
- backend/src/main/java/softeer/wantcar/cartalog/similarity/dto/SimilarEstimateListResponseDto.java
- backend/src/main/java/softeer/wantcar/cartalog/similarity/dto/SimilarEstimateResponseDto.java
- backend/src/main/java/softeer/wantcar/cartalog/similarity/dto/SimilarEstimateWithSideImageResponseDto.java
- backend/src/main/java/softeer/wantcar/cartalog/similarity/service/SimilarityService.java
- backend/src/main/java/softeer/wantcar/cartalog/similarity/service/SimilarityServiceImpl.java
> [Backend] 통합 유사 견적 조회 API 구현 #526

- frontend/src/components/PriceCompareBar/style.jsx
- frontend/src/components/SummaryPopup/index.jsx
- frontend/src/pages/EstimationPage/HMGArea/SimilarPopup/SimilarInfo/index.jsx
- frontend/src/pages/EstimationPage/HMGArea/SimilarPopup/SimilarInfo/style.jsx
- frontend/src/pages/EstimationPage/HMGArea/SimilarPopup/constants.js
- frontend/src/pages/EstimationPage/HMGArea/SimilarPopup/index.jsx
- frontend/src/pages/EstimationPage/HMGArea/SimilarPopup/style.jsx
- frontend/src/pages/EstimationPage/HMGArea/index.jsx
- frontend/src/pages/EstimationPage/index.jsx
- frontend/src/pages/ModelTypePage/Pick/HMGData/index.jsx
- frontend/src/pages/OptionPickerPage/Info/index.jsx
- frontend/src/utils/Context/index.jsx
- PriceCompareBar 컴포넌트 추가
- HashTag 컴포넌트 추가
- 유사 견적 캐러셀 구현
- 옵션 추가 시에 종료 모달 처리
- 옵션 추가 시에 버튼 모달 처리
- 유사 견적 모달에서 선택한 옵션 state 추가
- #376
> [Front-End] 유사 견적 모달 API 연동 및 구현

- frontend/src/hooks/useFetch.js
* useFetch 에러 발생 시 navigate 하지 않도록 수정
* useFetch 초기 값 반환 수정
> [Front-End] feat: useFetch 에러 처리 수정

- backend/src/main/java/softeer/wantcar/cartalog/similarity/repository/QueryString.java
- backend/src/test/java/softeer/wantcar/cartalog/similarity/repository/SimilarityQueryRepositoryTest.java
Reverts softeerbootcamp-2nd/H7-WantCar#528
> Revert "[Backend] 유사 견적 식별자 목록 조회 시 견적 간 서로 다른 해시태그 조합을 갖도록 변경"

- backend/src/main/java/softeer/wantcar/cartalog/similarity/repository/QueryString.java
- backend/src/test/java/softeer/wantcar/cartalog/similarity/repository/SimilarityQueryRepositoryTest.java
Reverts softeerbootcamp-2nd/H7-WantCar#533
> Revert "Revert "[Backend] 유사 견적 식별자 목록 조회 시 견적 간 서로 다른 해시태그 조합을 갖도록 변경""

- backend/src/main/java/softeer/wantcar/cartalog/estimate/controller/EstimateController.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/dto/EstimateRequestDto.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/repository/EstimateQueryRepository.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/repository/dto/EstimateCountDto.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/repository/dto/EstimateOptionIdListDto.java
- backend/src/main/java/softeer/wantcar/cartalog/model/dto/EstimateImageDto.java
Reverts softeerbootcamp-2nd/H7-WantCar#530
> Revert "[Backend] API 검증을 위한 임시 로그 추가"

- frontend/src/components/SummaryPopup/index.jsx
- frontend/src/pages/ModelTypePage/Pick/HMGData/index.jsx
- frontend/src/pages/ModelTypePage/index.jsx
- frontend/src/pages/OptionPickerPage/Info/index.jsx
* fetch할 때 url 상수 사용하도록 수정
* Close #536
> [Front-End] refactor: URL 상수 사용하도록 수정

- frontend/src/components/Interaction/index.jsx
* 다음 페이지 미리 렌더링하는 문제 수정
* Close #541
> [Front-End] fix: 다음 페이지 미리 렌더링하는 문제 수정

- frontend/src/pages/EstimationPage/Preview/CarImage/index.jsx
- frontend/src/pages/EstimationPage/Preview/CarImage/style.jsx
- frontend/src/pages/EstimationPage/Preview/index.jsx
- frontend/src/pages/EstimationPage/Preview/style.jsx
* 완료 페이지 외장 내장 이미지 크기 수정
* 외장 내장 전환 시 애니메이션 추가
* Close #543
> feat: 완료 페이지 이미지 크기 수정

- frontend/src/pages/EstimationPage/HMGArea/PriceCard/GraphArea/index.jsx
- frontend/src/pages/EstimationPage/HMGArea/PriceCard/index.jsx
- frontend/src/pages/EstimationPage/HMGArea/SimilarCard/index.jsx
- frontend/src/pages/EstimationPage/HMGArea/SimilarPopup/SimilarInfo/index.jsx
- frontend/src/pages/EstimationPage/HMGArea/SimilarPopup/index.jsx
- frontend/src/pages/EstimationPage/HMGArea/index.jsx
* 유사 견적 페이지 API 연결
* API 수정
* Close #545
> [Front-End] feat: 완료 페이지 유사 견적 팝업 API 연결

- frontend/src/pages/EstimationPage/HMGArea/SimilarCard/index.jsx
- frontend/src/pages/EstimationPage/HMGArea/SimilarPopup/SimilarInfo/index.jsx
- frontend/src/pages/EstimationPage/HMGArea/SimilarPopup/index.jsx
> [Front-End] feat: 유사 견적 팝업 완성

- frontend/src/pages/EstimationPage/Preview/CarImage/index.jsx
- frontend/src/pages/EstimationPage/Preview/style.jsx
* 완료 페이지 애니메이션 수정
* Close #552
> [Front-End] fix: 완료 페이지 애니메이션 수정

- frontend/index.html
- frontend/src/components/Guide/constants.js
- frontend/src/components/Guide/index.jsx
- frontend/src/components/Guide/style.jsx
- frontend/src/pages/TrimSelectPage/Info/HMGInfo/index.jsx
- frontend/src/pages/TrimSelectPage/Info/HMGInfo/style.jsx
- frontend/src/pages/TrimSelectPage/Info/index.jsx
- frontend/src/pages/TrimSelectPage/Info/style.jsx
- frontend/src/pages/TrimSelectPage/index.jsx
> [Front-End] feat: 온보딩 팝업 구현

- Android/app/src/main/java/com/softeer/cartalog/viewmodel/TypeViewModel.kt
> [Android] Final Code Refactoring #547
