softeerbootcamp-2nd/H7-WantCar

- frontend/src/components/Popup/index.jsx
- frontend/src/components/Popup/style.jsx
- frontend/src/styles/GlobalStyle.jsx
Close #82 
사용 예시 (전체 페이지):
``` js
function PopupTestPage() {
const [show, setShow] = useState(false);
const handleClose = () => setShow(false);
const actions = [
{ secondary: true, text: '취소' },
{ text: '확인', onClick: () => alert('확인') },
];
return (
<div style={{ padding: '100px' }}>
<button onClick={() => setShow(true)}>팝업 띄우는 버튼</button>
<Popup show={show} close={handleClose} actions={actions}>
Sample Popup
</Popup>
</div>
);
}
```
사용 예시 (팝업 컴포넌트만):
``` js
<Popup show={show} close={handleClose} actions={actions}>
Sample Popup
</Popup>
```
`show`: 팝업 표시 여부
`close`: 팝업 닫는 함수
`actions`: 팝업 하단에 표시될 액션 정보
`children`: 팝업에 표시될 메시지
> [Front-End] feat: Popup 컴포넌트 추가

- frontend/src/pages/ExteriorColorPage/Info/TrimImage/index.jsx
- frontend/src/pages/ExteriorColorPage/Info/TrimImage/style.jsx
- frontend/src/pages/ExteriorColorPage/Info/TrimStand/index.jsx
- frontend/src/pages/ExteriorColorPage/Info/TrimStand/style.jsx
- frontend/src/pages/ExteriorColorPage/Info/index.jsx
⚠️ border-image랑 border-radius는 같이 설정되지 않는다.
```
.btn-gradient-2 {
background: linear-gradient(white, white) padding-box,
linear-gradient(to right, darkblue, darkorchid) border-box;
border-radius: 50em;
border: 4px solid transparent;
}
```
border-radius 속성과 background 속성을 사용해서 대체하는 방법
선형 그래디언트 뒤에 지정된 'padding-box' 및 'border-box' 값은 배경을 나타낸다.
첫 번째 padding-box는 가짜 배경으로, border처럼 보이게 해준다.
두 번째 border-box는 border영역의 색을 나타내준다.
마지막으로 border에 transparent를 설정해서 border영역의 배경을 보이도록 해준다.
close #96
> [Front-End] Fe feature/#96

- backend/src/main/java/softeer/wantcar/cartalog/config/SwaggerConfig.java
Swagger를 통해 API 목록 및 명세를 보지 못하던 버그 해결
resolve: #125
> [Backend] Swagger를 통해 API 목록을 볼 수 있도록 수정

- backend/src/test/java/softeer/wantcar/cartalog/trim/repository/TrimQueryRepositoryTest.java
> [Backend] 트림 쿼리 Repository의 누락되었던 테스트 추가

- frontend/src/components/RoundButton/style.jsx
- frontend/src/pages/OptionPickerPage/Info/index.jsx
- frontend/src/pages/OptionPickerPage/Pick/CategorySelector/index.jsx
- frontend/src/pages/OptionPickerPage/Pick/CategorySelector/style.jsx
- frontend/src/pages/OptionPickerPage/Pick/TypeSelector/index.jsx
- frontend/src/pages/OptionPickerPage/Pick/TypeSelector/style.jsx
- frontend/src/pages/OptionPickerPage/Pick/index.jsx
- frontend/src/pages/OptionPickerPage/Pick/style.jsx
- frontend/src/pages/OptionPickerPage/index.jsx
옵션 선택 페이지 레이아웃 추가
* Mock data 이용해서 데이터 표시
* 페이지 내 state 이용해서 선택한 옵션 데이터 처리
* API 연결
* 카테고리 버튼 동작하도록 수정
* context api를 이용해서 다른 페이지로 상태 전달
* close #215
> [Front-End] feat: 옵션 선택 페이지 추가

- frontend/src/components/Header/Nav/index.jsx
- frontend/src/pages/ExteriorColorPage/Info/TrimImage/index.jsx
- frontend/src/pages/ExteriorColorPage/Pick/index.jsx
- frontend/src/pages/ExteriorColorPage/index.jsx
- frontend/src/utils/Context/index.jsx
새로 수정된 API로 반영 🐌
```jsx
setTrimState((prevState) => ({
...prevState,
exteriorColor: {
...exteriorColor,
fetchData: [...dataFetch.exteriorColors],
page: dataFetch.exteriorColors.length - 3,
isFetch: true,
name: defaultData.name,
carImageDirectory: defaultData.carImageDirectory,
carImageList: Array.from({ length: 60 }, (_, index) => {
const imageNumber = (index + 1).toString().padStart(3, '0');
return `${defaultData.carImageDirectory}${imageNumber}.png`;
}),
},
}));
```
`carImageList`에는 미리 60개의 자동차 이미지를 받아놓음
```jsx
return (
<S.TrimImage>
{exteriorColor.carImageList.map((imagePath, index) => (
<S.RotateImage
key={imagePath}
src={imagePath}
style={{ display: index === count ? 'block' : 'none' }}
onMouseMove={startSwipe}
/>
))}
</S.TrimImage>
);
```
`display:none`으로 이미지 미리 화면에 받아놓는 방식으로 수정 …
> [Front-End] 외장색상 API 수정 & 360도 수정 & Nav 수정

- frontend/src/pages/TrimSelectPage/Pick/index.jsx
- frontend/src/pages/TrimSelectPage/index.jsx
이전에 선택했던 트림을 다시 선택할 경우에는 그대로 데이터 유지
다른 트림을 선택할 경우에는 fetch 초기화
```jsx
const handleTrimCardClick = (trimData) => {
if (trimData.id === trim.Id) return;
setTrimState((prevState) => ({
...prevState,
trim: {
...prevState.trim,
Id: trimData.id,
},
modelType: {
...prevState.modelType,
isFetch: false,
},
exteriorColor: {
...prevState.exteriorColor,
isFetch: false,
},
interiorColor: {
...prevState.interiorColor,
isFetch: false,
},
optionPicker: {
...prevState.optionPicker,
isFetch: false,
},
}));
};
```
- close #238
> [Front-End] 다른 트림 선택 시에 fetch 초기화

- backend/src/main/java/softeer/wantcar/cartalog/global/ServerPath.java
- backend/src/main/java/softeer/wantcar/cartalog/global/dto/HMGDataDto.java
- backend/src/main/java/softeer/wantcar/cartalog/global/dto/PowerTrainHMGDataDto.java
- backend/src/main/java/softeer/wantcar/cartalog/model/repository/ModelQueryRepository.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/controller/TrimOptionController.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/dto/TrimInteriorColorListResponseDto.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/dto/TrimOptionListResponseDto.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/repository/QueryString.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/repository/TrimColorQueryRepositoryImpl.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/repository/TrimOptionQueryRepository.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/repository/TrimOptionQueryRepositoryImpl.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/service/TrimOptionService.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/service/TrimOptionServiceImpl.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/service/TrimQueryService.java
- backend/src/test/java/softeer/wantcar/cartalog/trim/controller/TrimColorControllerTest.java
- backend/src/test/java/softeer/wantcar/cartalog/trim/controller/TrimOptionControllerTest.java
- backend/src/test/java/softeer/wantcar/cartalog/trim/repository/TrimColorQueryRepositoryImplTest.java
- backend/src/test/java/softeer/wantcar/cartalog/trim/repository/TrimOptionQueryRepositoryTest.java
- backend/src/test/java/softeer/wantcar/cartalog/trim/repository/TrimQueryRepositoryTest.java
- backend/src/test/java/softeer/wantcar/cartalog/trim/service/TrimOptionServiceTest.java
- backend/src/test/resources/csv/model_option_parent_categories.csv
- backend/src/test/resources/schema.sql
> [Backend] 옵션 정보 목록 조회 API 구현 #116

- frontend/src/hooks/useIntersectionObserver.js
* useIntersectionObserver 훅 추가
> 컴포넌트가 화면에 보이는지 감지해서 화면에 보일 때 애니메이션을 시작할 수 있음
```javascript
function SampleComponent({ children }) {
const targetRef = useRef();
const isInViewport = useIntersectionObserver(targetRef);
const className = isInViewport ? 'rendered' : '';
return <div className={className} ref={targetRef}>{children}</div>;
}
```
* Close #266
> [Front-End] feat: useIntersectionObserver 훅 추가

- backend/src/main/java/softeer/wantcar/cartalog/model/controller/ModelController.java
- backend/src/main/java/softeer/wantcar/cartalog/model/repository/ModelOptionQueryRepository.java
- backend/src/main/java/softeer/wantcar/cartalog/model/repository/ModelOptionQueryRepositoryImpl.java
- backend/src/test/java/softeer/wantcar/cartalog/CartalogApplicationTests.java
- backend/src/test/java/softeer/wantcar/cartalog/model/controller/ModelControllerTest.java
- backend/src/test/java/softeer/wantcar/cartalog/model/repository/ModelOptionQueryRepositoryImplTest.java
> [Backend] 모델 타입 옵션 쿼리 수정

- frontend/src/App.css
- frontend/src/App.jsx
- frontend/src/components/Header/Nav/index.jsx
- frontend/src/components/Header/Nav/style.jsx
- frontend/src/components/NextButton/index.jsx
- frontend/src/components/Section/index.jsx
- frontend/src/pages/ExteriorColorPage/index.jsx
- frontend/src/pages/InteriorColorPage/index.jsx
- frontend/src/pages/ModelTypePage/index.jsx
- frontend/src/pages/OptionPickerPage/index.jsx
- frontend/src/pages/TrimSelectPage/Pick/TrimCard/index.jsx
- frontend/src/pages/TrimSelectPage/index.jsx
- frontend/src/utils/Context/index.jsx
현재 링크와 다음 링크의 순서를 비교해서 애니메이션을 적용
```js
export function StartAnimation(nowPath, nextPath, navigate, setTrimState, pagePath) {
navigate(nextPath);
if (pagePath[nextPath] > pagePath[nowPath]) {
setTrimState((prevState) => ({
...prevState,
movePage: {
...prevState.movePage,
nowContentRef: 'leftNowLoad',
nextContentRef: 'leftNextLoad',
},
}));
}
if (pagePath[nextPath] < pagePath[nowPath]) {
setTrimState((prevState) => ({
...prevState,
movePage: {
...prevState.movePage,
nowContentRef: 'rightNowLoad',
nextContentRef: 'rightNextLoad',
},
}));
}
}
```
- close #232
> [Front-End] 라우터 캐러쉘 적용

- backend/src/main/java/softeer/wantcar/cartalog/trim/dto/TrimListResponseDto.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/repository/QueryString.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/repository/TrimQueryRepositoryImpl.java
- backend/src/test/java/softeer/wantcar/cartalog/trim/repository/TrimQueryRepositoryTest.java
> [Backend] 트림 목록 조회 Api 항목 추가 #273

- frontend/src/components/Interaction/index.jsx
* 브라우저 width가 1200px보다 작을 때 이전 페이지 요소가 보이는 문제 수정
* Close #309
> [Front-End] fix: 브라우저 width 줄어들었을 때 레이아웃 깨지는 문제 수정

- backend/src/main/java/softeer/wantcar/cartalog/estimate/controller/SimilarityController.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/dto/SimilarEstimateDto.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/dto/SimilarEstimateResponseDto.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/repository/EstimateQueryRepository.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/repository/EstimateQueryRepositoryImpl.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/repository/QueryString.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/repository/SimilarityCommandRepository.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/repository/SimilarityCommandRepositoryImpl.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/repository/SimilarityQueryRepository.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/repository/SimilarityQueryRepositoryImpl.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/repository/dto/EstimateInfoDto.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/repository/dto/EstimateOptionInfoDto.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/repository/dto/EstimateOptionListDto.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/repository/dto/HashTagMap.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/service/SimilarityService.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/service/SimilarityServiceImpl.java
- backend/src/main/java/softeer/wantcar/cartalog/model/controller/ModelController.java
- backend/src/main/java/softeer/wantcar/cartalog/model/repository/ModelOptionQueryRepository.java
- backend/src/main/java/softeer/wantcar/cartalog/model/repository/ModelOptionQueryRepositoryImpl.java
- backend/src/main/java/softeer/wantcar/cartalog/model/repository/QueryString.java
- backend/src/main/java/softeer/wantcar/cartalog/trim/service/TrimOptionService.java
- backend/src/test/java/softeer/wantcar/cartalog/estimate/controller/EstimateControllerTest.java
- backend/src/test/java/softeer/wantcar/cartalog/estimate/controller/SimilarityControllerTest.java
- backend/src/test/java/softeer/wantcar/cartalog/estimate/repository/EstimateQueryRepositoryTest.java
- backend/src/test/java/softeer/wantcar/cartalog/estimate/repository/SimilarityCommandRepositoryTest.java
- backend/src/test/java/softeer/wantcar/cartalog/estimate/repository/SimilarityQueryRepositoryTest.java
- backend/src/test/java/softeer/wantcar/cartalog/estimate/service/SimilarityServiceTest.java
- backend/src/test/java/softeer/wantcar/cartalog/model/repository/ModelOptionQueryRepositoryImplTest.java
- backend/src/test/resources/csv/similar_estimates.csv
- backend/src/test/resources/schema.sql
> [Backend] 유사 출고 견적 조회 API 구현 #119

- frontend/src/pages/EstimationPage/Detail/DetailCard/DetailTitle/index.jsx
- frontend/src/pages/EstimationPage/Detail/DetailCard/index.jsx
- frontend/src/pages/EstimationPage/Footer/index.jsx
- frontend/src/pages/EstimationPage/Footer/style.jsx
- frontend/src/pages/EstimationPage/Preview/style.jsx
- frontend/src/pages/EstimationPage/constants.js
- frontend/src/pages/EstimationPage/index.jsx
- frontend/src/pages/EstimationPage/style.jsx
- 완료 페이지 Footer 버튼 설정 
- 상세견적 Tab 조건부 렌더링 적용
이미지 확인 버튼에서 상단으로 가지 않는 문제
```js
const imageViewButtonProps = {
onClick: () => {
console.log('click');
window.scrollTo({
top: 0,
behavior: 'smooth',
});
},
text: FOOTER.CHECK_IMAGE,
};
```
- #363
> [Front-End] 완료 페이지 Footer 설정 및 상세견적 Tab 조건부 렌더링

- frontend/src/components/Header/Exit/index.jsx
- frontend/src/components/Header/Logo/index.jsx
- frontend/src/components/Popup/index.jsx
* Popup 컴포넌트의 overlay가 일부 컴포넌트를 가리지 않는 문제 수정
* 헤더의 Logo, Exit를 통해 열린 Popup의 close가 동작하지 않는 문제 수정
* Close #390
> [Front-End] Popup 컴포넌트, 헤더 Logo, Exit 버그 수정

- frontend/src/components/Interaction/index.jsx
- history로 뒤로가기 이벤트 추가
- isFetch가 false일 경우 뒤로가기 예외처리
isFetch가 false일 경우에는 history를 replace해서 처리함
```js
if (!canGoBack) {
const { nowPage } = history.state;
if (nowPage !== data.page) {
history.replaceState({ nowPage: data.page }, '');
return;
}
}
```
- #372
> [Front-End] history로 뒤로가기 이벤트 추가

- backend/src/main/java/softeer/wantcar/cartalog/estimate/service/SimilarityServiceImpl.java
- backend/src/main/java/softeer/wantcar/cartalog/similarity/repository/QueryString.java
- 옵션 또는 패키지가 선택되지 않은 견적서의 유사 견적 개수 조회 시 에러가 발생하는 문제 해결
- 이전에는 에러가 발생하는 두 부분 중 한 곳만 수정되었었음
> [Backend] 여전히 옵션 또는 패키지가 선택되지 않은 견적서의 유사 견적 개수 조회 시 에러가 발생하는 문제 해결

- Android/app/src/main/java/com/softeer/cartalog/ui/adapter/ButtonBindingAdapters.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/fragment/ConfirmFragment.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/fragment/ExteriorFragment.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/fragment/InteriorFragment.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/fragment/OptionFragment.kt
- Android/app/src/main/java/com/softeer/cartalog/ui/fragment/TypeFragment.kt
- Android/app/src/main/java/com/softeer/cartalog/util/UtilManager.kt
`onBackPressed` 를 `override`해서 구현하는 방식은 Deprecated 되어서, 
`onBackPressedCallback` 를 사용하여 뒤로가기 시나리오를 구현하였음.
> [Android] Back버튼 클릭 시나리오 회의 및 구현 #409

- backend/src/main/java/softeer/wantcar/cartalog/similarity/repository/SimilarityQueryRepositoryImpl.java
- backend/src/test/java/softeer/wantcar/cartalog/similarity/repository/SimilarityQueryRepositoryTest.java
> [Backend] 유사 견적 조회 API가 실패하는 버그 해결

- frontend/src/components/PriceGraph/index.jsx
* 가격 분포 그래프에서  오류 해결 Warning: `NaN` is an invalid value for the `left` css style property. 에러 생기는 문제 해결
* Close #511
> [Front-End] fix: 가격 분포 그래프 오류 해결

- backend/src/main/java/softeer/wantcar/cartalog/estimate/dto/EstimateCountInfoDto.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/repository/QueryString.java
- backend/src/main/java/softeer/wantcar/cartalog/estimate/repository/dto/EstimateCountDto.java
- backend/src/main/java/softeer/wantcar/cartalog/similarity/controller/SimilarityController.java
- backend/src/main/java/softeer/wantcar/cartalog/similarity/service/SimilarityServiceImpl.java
- backend/src/test/java/softeer/wantcar/cartalog/estimate/repository/EstimateQueryRepositoryTest.java
- backend/src/test/java/softeer/wantcar/cartalog/similarity/controller/SimilarityControllerTest.java
- backend/src/test/java/softeer/wantcar/cartalog/similarity/service/SimilarityServiceTest.java
> [Backend] 클라이언트의 요구사항에 맞게 유사 견적 개수 조회 시 유사 견적의 가격도 같이 제공하도록 변경
